# https://github.com/prometheus/blackbox_exporter/blob/master/blackbox.yml 참조
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: monitoring
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200, 302, 403]
          method: GET