
es: 
  uri: https://elastic:straight1234!@:elasticsearch-master.str-logging.svc.cluster.local:9200
  sslSkipVerify: true
serviceMonitor:
  enabled: true
  namespace: str-monitoring
  labels:
    release: prometheus