replicaCount: 1

image:
  repository: chamilad/kibana-prometheus-exporter
  tag: v8.7.x.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

extraArgs:
  kibana.uri: "http://kibana.str-logging.svc.cluster.local:5601"
  kibana.username: "elastic"
  kibana.password: "straight1234!"

serviceMonitor:
  enabled: true
  namespace: str-monitoring
  additionalLabels:
    release: prometheus
