replicaCount: 1

image:
  repository: chamilad/kibana-prometheus-exporter
  tag: v8.7.x.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

extraArgs:
  kibana.uri: "http://kibana:5601"
  kibana.username: "straight"
  kibana.password: "straight1234!"