apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: str-monitoring
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      nodeSelector:
        environment: "operation"
      containers:
      - name: postgres-exporter
        image: wrouesnel/postgres_exporter:latest
        ports:
        - containerPort: 9187
          name: metrics
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: data-source-name
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: str-monitoring
type: Opaque
stringData:
  data-source-name: "postgres://postgres:straight6scraping!@3.38.80.105:5432/postgres?sslmode=disable&connect_timeout=10"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: str-monitoring
  labels:
    app: postgres-exporter
spec:
  ports:
  - port: 9187
    targetPort: metrics
    name: metrics
  selector:
    app: postgres-exporter