apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics-monitor
  namespace: monitoring  # Prometheus가 설치된 네임스페이스
  labels:
    release: prometheus  # Prometheus Helm release 이름과 동일해야 함
spec:
  namespaceSelector:
    matchNames:
      - argocd           # ArgoCD 네임스페이스 지정
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
