apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chatbot-metrics-monitor
  namespace: monitoring              # Prometheus Operator가 설치된 네임스페이스
  labels:
    release: prometheus              # Prometheus Helm release 이름과 동일하게 설정
spec:
  namespaceSelector:
    matchNames:
      - straight-dev                 # 메트릭을 수집할 서비스가 속한 네임스페이스
  selector:
    matchLabels:
      app.kubernetes.io/instance: chatbot-dev   # 서비스 레이블 매칭
      app.kubernetes.io/name: straight
  endpoints:
    - port: prometheus                # 서비스의 'prometheus' 포트 이름
      path: /actuator/prometheus      # Spring Boot Actuator 메트릭 경로
      interval: 30s                   # 메트릭 수집 주기 (필요에 따라 조정)
