# custom-values.yaml
prometheus:
  prometheusSpec:
    # additionalScrapeConfigsSecret.enabled = false → ConfigMap을 사용
    additionalScrapeConfigsSecret:
      enabled: false

    # additionalScrapeConfigs: ConfigMap 의 metadata.name / data key
    additionalScrapeConfigs:
     - job_name: 'harbor-metrics'
       scrape_interval: 30s
       metrics_path: /metrics
       scheme: http
       static_configs:
         - targets:
           - "3.39.180.201:9090"
     - job_name: 'jenkins-metrics'
       scrape_interval: 30s
       metrics_path: /prometheus
       scheme: http
       static_configs:
         - targets:
           - "3.35.96.221:8080"
     - job_name: 'harbor-blackbox'
       metrics_path: /probe
       params:
         module: [http_2xx]  # Refers to the module defined in blackbox.yml
       static_configs:
         - targets:
           - "https://harbor.sw-staring.com"  # Full URL with scheme
       relabel_configs:
         - source_labels: [__address__]
           target_label: __param_target
         - target_label: __address__
           replacement: blackbox-exporter.monitoring.svc.cluster.local:9115  # Blackbox Exporter's address
alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_interval: 15s 
      group_wait: 5s # alert 버퍼를 몇초동안 유지할 것인지
      receiver: default-slack-alert
      repeat_interval: 12h
      routes:
      - match:
          class: harbor
        receiver: 'harbor-slack-alert'
    receivers:
    - name: 'default-slack-alert' # Blackhole
    - name: 'harbor-slack-alert'
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#harbor-notice'
        send_resolved: true
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname']

