apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: probe-http-status-alert
  namespace: monitoring
  labels: 
    release: prometheus
spec:
  groups:
  - name: http-probe-alerts
    rules:
    - alert: HarborStatusNotHealthy
      expr: probe_http_status_code{job="harbor-blackbox"} != 200
      for: 1m
      labels:
        severity: warning
        class: harbor
      annotations:
        summary: "Harbor Status is not Healthy"
        description: |
          Harbor Status Code is {{ $value }}.
          This alert is triggered when the HTTP status code is not 200.
          Check the probe target for issues.