apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: postgres-rules
  namespace: str-monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: postgres.rules
    rules:
    - alert: PostgreSQLHighConnections
      expr: pg_stat_activity_count > 100
      for: 5m
      labels:
        severity: warning
        class: postgresql
      annotations:
        summary: "PostgreSQL 연결 수가 높음"
        description: "데이터베이스 {{ $labels.datname }}의 연결 수가 100개를 초과했습니다: {{ $value }}"
        action_guide: |
          확인이 필요한 사항:
          1. 현재 활성 연결 확인
             - SELECT * FROM pg_stat_activity;
          2. 오래된 연결 정리
             - SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE ...;
          3. 커넥션 풀 설정 검토

    - alert: PostgreSQLReplicationLag
      expr: pg_stat_replication_lag_bytes > 10000000
      for: 5m
      labels:
        severity: critical
        class: postgresql
      annotations:
        summary: "PostgreSQL 복제 지연 발생"
        description: "복제 지연이 10MB를 초과했습니다: {{ $value }} bytes"
        action_guide: |
          확인이 필요한 사항:
          1. 복제 상태 확인
             - SELECT * FROM pg_stat_replication;
          2. 네트워크 상태 확인
          3. 슬레이브 서버 리소스 상태 확인

    - alert: PostgreSQLSlowQueries
      expr: rate(pg_stat_activity_max_tx_duration{datname!~"template.*"}[5m]) > 300
      for: 5m
      labels:
        severity: warning
        class: postgresql
      annotations:
        summary: "PostgreSQL 느린 쿼리 감지"
        description: "데이터베이스 {{ $labels.datname }}에서 5분 이상 실행 중인 쿼리가 있습니다"
        action_guide: |
          확인이 필요한 사항:
          1. 실행 중인 쿼리 확인
             - SELECT * FROM pg_stat_activity WHERE state = 'active';
          2. 쿼리 실행 계획 분석
          3. 필요시 문제 쿼리 종료 