{
 "title": "Kibana",
 "tags": [ "kibana" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime in Days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kibana_millis_uptime/1000/60/60/60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kibana_heap_used_in_bytes/kibana_heap_max_in_bytes)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kibana_os_memory_used_in_bytes/kibana_os_memory_max_in_bytes)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident Set Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((kibana_resident_set_size_in_bytes/1024/1024)/(kibana_os_memory_max_in_bytes/1024/1024))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kibana_concurrent_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Overall Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    { "expr": "kibana_status", "legendFormat": "__auto" },
    { "expr": "kibana_core_es_status", "legendFormat": "__auto" },
    {
     "expr": "kibana_core_savedobjects_status",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Kibana Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kibana_heap_max_in_bytes/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "kibana_heap_used_in_bytes/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kibana_os_memory_max_in_bytes/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "kibana_os_memory_used_in_bytes/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kibana_os_load_1m", "legendFormat": "__auto" },
    { "expr": "kibana_os_load_5m", "legendFormat": "__auto" },
    { "expr": "kibana_os_load_15m", "legendFormat": "__auto" }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Concurrent Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kibana_concurrent_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kibana_requests_total", "legendFormat": "__auto" },
    { "expr": "kibana_requests_disconnects", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kibana_response_average", "legendFormat": "__auto" },
    { "expr": "kibana_response_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NodeJS Event Loop Delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kibana_event_loop_delay", "legendFormat": "__auto" }
   ]
  }
 ]
}