apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: probe-http-status-alert
  namespace: monitoring
  labels: 
    release: prometheus
spec:
  groups:
  - name: http-probe-alerts
    rules:
    - alert: HarborStatusNotHealthy
      expr: probe_http_status_code{job="harbor-blackbox"} != 200
      for: 1m
      labels:
        severity: warning
        class: harbor
      annotations:
        summary: "Harbor Status is not Healthy"
        description: |
          Harbor Status Code is {{ $value }}.
          This alert is triggered when the HTTP status code is not 200.
          Check the probe target for issues.
  - name: argocd-rules
    rules:
    - alert: ArgocdApplicationHealth
      expr: argocd_app_info{health!="Healthy"} > 0
      for: 5m
      labels:
        severity: critical
        class: argocd
      annotations:
        summary: "Argocd Application Health Alert"
        description: "One or more Argocd applications are not healthy."
    - alert: ArgoAppNotSynced
      expr: argocd_app_info{sync_status!="Synced"} > 0
      for: 12h
      labels:
        severity: warning
      annotations:
        summary: "[{{`{{$labels.name}}`}}] Application not synchronized"
        description: "The application [{{`{{$labels.name}}`}}] has not been synchronized for over 12 hours."
    - alert: ArgocdServerDown
      expr: up{job="argocd-server-metrics"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Argocd Server Down"
        description: "The Argocd server is not reachable."
    - alert: ArgocdApplicationControllerDown
      expr: up{job="argocd-application-controller-metrics"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Argocd Application Controller Down"
        description: "The Argocd application controller is not reachable."
    - alert: ArgoAppRollback
      expr: argocd_app_sync_total{phase="Failed"} > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "[{{`{{$labels.name}}`}}] Application Rollback Detected"
        description: "The application [{{`{{$labels.name}}`}}] has encountered a rollback due to failed sync."