# redis-exporter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: redis
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.52.0
        ports:
        - containerPort: 9121
        args:
          - "--redis.addr=redis://redis-svc-headless.redis.svc.cluster.local:6379"
          - "--is-cluster=true"
          - "--export-client-list=true"
          - "--export-client-port=true"
          - "--include-config-metrics=true"
          - "--include-system-metrics=true"
          - "--export-client-list=true"
          - "--export-client-port=true"
          - "--export-client-list=true"
          # Key Metrics
          - "--check-keys=*"  # 모든 키 패턴 체크 (필요에 따라 조정)
          - "--check-key-groups=*"  # 키 그룹 체크 (필요에 따라 조정)
          - "--check-single-keys=*"  # 단일 키 체크 (필요에 따라 조정)
          - "--check-streams=*"  # 스트림 체크 (필요에 따라 조정)
          # Additional Metrics
          - "--export-client-list=true"
          - "--export-client-port=true"
          - "--include-config-metrics=true"
          - "--include-system-metrics=true"
        # env:
        # - name: REDIS_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: redis-password
        #       key: password
        # # 필요 시 TLS 설정 추가
        # # - "--tls-server-ca-cert-file=/path/to/ca.crt"
        # # - "--tls-server-cert-file=/path/to/server.crt"
        # # - "--tls-server-key-file=/path/to/server.key"
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 5
          periodSeconds: 10
---
# redis-exporter-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: redis
  labels:
    app: redis-exporter
spec:
  ports:
  - name: metrics
    port: 9121
    targetPort: 9121
  selector:
    app: redis-exporter